# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='phone_number_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='phone_number_2',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Kenya', max_length=120),
        ),
    ]
