# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='billing_profile',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
