branch-defaults:
  master:
    environment: Foodstore-env
    group_suffix: null
environment-defaults:
  Foodstore-env:
    branch: null
    repository: null
global:
  application_name: foodstore
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
