# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180422_0333'),
        ('carts', '0005_auto_20180520_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
