# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180422_0333'),
        ('carts', '0006_auto_20180520_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
