# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20180521_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
