from django.conf.urls import url

from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        ProductDownloadView,
        Vegetables,
        TomatoesOnions,
        PotatoesRoots,
        CupBoard,
        Fruits,
        Milk,
        Meat,
        Drinks,
        Spinach,
        CategoryList,
        Cabbage,
        Managu,
        Pumpkin,
        PumpkinLeaves,
        Peas,
        Lettuce,
        Brocolli,
        Mushroom,
        Butternut,
        Beetroot,
        Beans,
        Maize,
        Kales,
        Cucumber,
        Watermelon,
        Bananas,
        Mango,
        Oranges,
        Apples,
        Strawberry,
        Avocado,
        Lemon,
        Guava,
        Grape,
        Pineapples,
        Pear,
        Passion,
        Tomatoes,
        GreenOnions,
        YellowOnions,
        RedOnions,
        Garlic,
        PilipiliHoho,
        DaikonRadish,
        Leeks,
        Zuchini,
        LeafyOnions,
        Jicama,
        Dhania,
        GreenRedChilli,
        Potatoes,
        SweetPotatoes,
        Carrots,
        Cassava,
        PasturisedMilk,
        NonPasturisedMilk,
        Mursik









 )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Vegetables.as_view(), name='Vegetables'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  TomatoesOnions.as_view(), name='tomatoesonions'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  CupBoard.as_view(), name='cup_board'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  PotatoesRoots.as_view(), name='potatoesrootsS'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Fruits.as_view(), name='fruits'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Milk.as_view(), name='milk'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Meat.as_view(), name='meat'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Drinks.as_view(), name='drinks'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Spinach.as_view(), name='spinach'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Cabbage.as_view(), name='cabbage'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Managu.as_view(), name='managu'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Pumpkin.as_view(), name='pumpkin'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  PumpkinLeaves.as_view(), name='pumpkinleaves'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Peas.as_view(), name='peas'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Lettuce.as_view(), name='lettuce'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Brocolli.as_view(), name='brocolli'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Mushroom.as_view(), name='mushroom'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Butternut.as_view(), name='butternut'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Beetroot.as_view(), name='beetroot'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Beans.as_view(), name='beans'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Maize.as_view(), name='maize'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Kales.as_view(), name='kales'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Cucumber.as_view(), name='cucumber'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Watermelon.as_view(), name='watermelon'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Bananas.as_view(), name='bananas'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Mango.as_view(), name='mango'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Oranges.as_view(), name='oranges'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Apples.as_view(), name='apples'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Strawberry.as_view(), name='strawberry'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Avocado.as_view(), name='avocado'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Lemon.as_view(), name='lemon'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Guava.as_view(), name='guava'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Grape.as_view(), name='grape'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Pineapples.as_view(), name='pineapples'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Pear.as_view(), name='pear'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Passion.as_view(), name='passion'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Tomatoes.as_view(), name='tomatoes'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  GreenOnions.as_view(), name='greenonions'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  RedOnions.as_view(), name='redonions'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  YellowOnions.as_view(), name='yellowonions'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Garlic.as_view(), name='garlic'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  PilipiliHoho.as_view(), name='pilipilihoho'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  DaikonRadish.as_view(), name='daikonradish'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Leeks.as_view(), name='leeks'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Zuchini.as_view(), name='zuchini'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  LeafyOnions.as_view(), name='leafyonions'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Jicama.as_view(), name='jicama'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Dhania.as_view(), name='dhania'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  GreenRedChilli.as_view(), name='greenredchilli'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Potatoes.as_view(), name='potatoes'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  SweetPotatoes.as_view(), name='sweetpotatoes'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Carrots.as_view(), name='carrots'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Cassava.as_view(), name='cassava'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  PasturisedMilk.as_view(), name='pasturisedmilk'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  NonPasturisedMilk.as_view(), name='nonpasturisedmilk'),
    url(r'^(?P<category_slug>[\w-]+)/(?P<pk>\d+)/$',  Mursik.as_view(), name='mursik'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', CategoryList.as_view(), name='category_list')
]
