# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-14 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180714_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category2',
            new_name='subcategory',
        ),
    ]
